CREATE SEQUENCE seq_cliente
    START WITH 1
    INCREMENT BY 15;

CREATE TABLE cliente (
    id BIGINT DEFAULT nextval('seq_cliente') PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sobrenome VARCHAR(100) NOT NULL,
    documento VARCHAR(18) NOT NULL UNIQUE ,
    email VARCHAR(70) NOT NULL UNIQUE ,
    tipo_cliente VARCHAR(20) NOT NULL,
    saldo DECIMAL(15,2) DEFAULT 0.00 CHECK (saldo >= 0),
    data_criacao TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER SEQUENCE seq_cliente OWNED BY cliente.id;

CREATE TABLE transferencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor DECIMAL(15, 2),
    remetente_id BIGINT NOT NULL,
    destinatario_id BIGINT NOT NULL,
    CONSTRAINT fk_transferencia_remetente FOREIGN KEY (remetente_id) REFERENCES cliente(id),
    CONSTRAINT fk_transferencia_destinatario FOREIGN KEY (destinatario_id) REFERENCES cliente(id)
);